-- ============================================================
-- MI MASCOTA CLUB · v29  —  NO CORRER
--
-- Este parche nunca se corrió y quedó REEMPLAZADO por
-- supabase-fundador-verificado-v30.sql (3 de octubre de 2026).
--
-- El v29 activaba el pase confiando en el número de operación que
-- venía en la dirección de /gracias, sin preguntarle a Mercado Pago,
-- y además redefinía socio_existe() con otra forma de respuesta, lo
-- que habría roto el acceso a Mi Mascota ID.
-- ============================================================
